export const SET_CREATION_STATE = 'SET_CREATION_STATE';
export const SET_ALL_ACTIVITIES = 'SET_ALL_ACTIVITIES';
export const SET_ACTIVITY_LIST = 'SET_ACTIVITY_LIST';
export const UPDATE_ACTIVITY_LIST = 'UPDATE_ACTIVITY_LIST';
export const SEARCH_ACTIVITY_LIST = 'SEARCH_ACTIVITY_LIST';
export const SET_ACTIVITY = 'SET_ACTIVITY';
export const SET_SEARCH_VAL ='SET_SEARCH_VAL';
